### ISSUE TITLE
补充几个

### ISSUE THREAD

**Issue by zurmokeeper** [gamedilong/awesome-nodejs-cn#1]
函数式编程：immer 不可变数据的特性 https://github.com/immerjs/immer
任务队列 ： 
                1：amqplib rabbit等等消息队列连接库  https://github.com/squaremo/amqp.node
                2：kafka-node kafka客户端  https://github.com/SOHU-Co/kafka-node
安全相关： helmet 常见攻击防御库，比如xss等等 https://github.com/helmetjs/helmet
数字：  decimal.js  -浮点计算  https://github.com/MikeMcl/decimal.js

**Comment by gamedilong** [comment]
加上去了哈
